package edu.andreasgut.MuehleWebSpringBoot;

import org.springframework.web.socket.TextMessage;
import org.springframework.web.socket.WebSocketSession;

import java.io.IOException;
import java.time.LocalTime;
import java.util.HashMap;

public class GameManager {

    private static HashMap<String, Game> gameMap = new HashMap<>();
    private static int autoGeneratedGameCode = 1;

    public static synchronized void addGame(String gameCode, Game game){
        gameMap.put(gameCode, game);
        System.out.println(LocalTime.now() + " – " + "Gamemanager: Game mit dem Gamecode " + gameCode + " hinzugefügt");
    }

    public static synchronized String generateGameCode(){
        String gameCode = "autogenerated" + autoGeneratedGameCode++;
        return gameCode;
    }

    static public synchronized void removeGame(String gameCode){
        gameMap.remove(gameCode);
        System.out.println(LocalTime.now() + " – " + "Gamemanager: Game mit dem Gamecode " + gameCode + " entfernt");
    }

    public static synchronized Game getGame(String gameCode){
        return gameMap.get(gameCode);
    }

    public static synchronized boolean doesGameExist(String gameCode){
        return gameMap.containsKey(gameCode);
   }

   public static synchronized boolean hasGameAlreadyStarted(String gameCode) {
        return gameMap.get(gameCode).isGameStarted();
    }
}
