package edu.andreasgut.MuehleWebSpringBoot;

import java.time.LocalTime;
import java.util.HashMap;

public class GameManager {

    HashMap<String, Game> gameMap = new HashMap<>();
    long autoGeneratedGameCode = 1;

    public void addGame(String gameCode, Game game){
        gameMap.put(gameCode, game);
        System.out.println(LocalTime.now() + " – " + this.getClass().getSimpleName() + ": Game mit dem Gamecode " + gameCode + " hinzugefügt");
    }

    public String addGameAndGetGameCode(Game game){
        String gameCode = "autogenerated" + autoGeneratedGameCode++;
        gameMap.put(gameCode, game);
        System.out.println(LocalTime.now() + " – " + this.getClass().getSimpleName() + ": Game mit dem Gamecode " + gameCode + " hinzugefügt");
        return gameCode;
    }

    public Game getGame(String gameCode){
        return gameMap.get(gameCode);
    }

   public boolean checkIfGameExists(String gameCode){
        return gameMap.containsKey(gameCode);
   }
}
